name: Run Postman Collection

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Install Node.js (Newman requires Node.js)
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the Node version

    # Step 3: Install Newman
    - name: Install Newman
      run: npm install -g newman

    # Step 4: Run the Postman collection with Newman
    - name: Run Postman Collection
      run: |
        newman run collection.json \
          -e environment.json \  # Use this line only if you have an environment file
          --reporters cli,junit \
          --reporter-junit-export results.xml

    # Step 5: Upload the test report as an artifact (optional)
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: postman-test-results
        path: results.xml